# set scroll history to 100,000 lines
set-option -g history-limit 100000

# modern colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"

# get links working
set -ga terminal-features "*:hyperlinks"

# VIM mode
set -g mode-keys vi

# because neovim wants it
set-option -g focus-events on

# Move between panes with vi keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

######################
### DESIGN CHANGES ###
######################

set -g status-left-length 20

set-option -g status-style "fg=white,bg=black"
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
set -g status-right "#[fg=cyan,bg=black,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "

# Alert-aware powerline window segments.
set -g @win_bg "#{?window_bell_flag,yellow,brightblack}"
set -g @win_fg "#{?window_bell_flag,black,white}"
set -g @win_attr "none"
set -g window-status-format "#[fg=black,bg=#{E:@win_bg},nobold,noitalics,nounderscore] #[fg=#{E:@win_fg},bg=#{E:@win_bg},#{E:@win_attr}]#I #[fg=#{E:@win_fg},bg=#{E:@win_bg},nobold,noitalics,nounderscore] #[fg=#{E:@win_fg},bg=#{E:@win_bg},#{E:@win_attr}]#W #[fg=#{E:@win_bg},bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-bell-style "fg=black,bg=yellow"
set -g window-status-activity-style "fg=white,bg=brightblack"
set -g window-status-separator ""
setw -g monitor-activity on
set -g bell-action any
set -g visual-bell off
set -g visual-activity off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

bind Tab switch-client -l

bind c new-window -c "#{pane_current_path}"
bind C new-window


bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
